############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: proxyserver002-letsencrypt-issuer
  namespace: proxyserver002
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: elias.dehondt@outlook.com
    privateKeySecretRef:
      name: proxyserver002-letsencrypt-issuer-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
---