############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Namespace
metadata:
  name: webserver004
  labels:
    name: webserver004
    app: webserver004
    owner: Zizis
    environment: production
  annotations:
    description: This namespace is used for the webserver004 application.
    contact: info@eliasdh.com
---