############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-deployment
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        kubernetes.io/hostname: node05
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Amsterdam"
        volumeMounts:
        - name: jellyfin-pvc-1
          mountPath: /config
        - name: jellyfin-pvc-1
          mountPath: /films
        - name: jellyfin-pvc-2
          mountPath: /series
      volumes:
      - name: jellyfin-pvc-1
        persistentVolumeClaim:
          claimName: jellyfin-pvc-1
      - name: jellyfin-pvc-2
        persistentVolumeClaim:
          claimName: jellyfin-pvc-2
---