############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Namespace
metadata:
  name: nicehash
  labels:
    name: nicehash
    app: nicehash
    owner: EliasDH
    environment: production
  annotations:
    description: This namespace is used for the nicehash application.
    contact: info@eliasdh.com
---