############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: netbox-housekeeping
  namespace: netbox
spec:
  schedule: "0 0 * * *" # Daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: housekeeping
            image: ghcr.io/eliasdhcom/netbox:latest
            imagePullPolicy: Always
            command: ["/opt/netbox/venv/bin/python", "/opt/netbox/netbox/manage.py", "housekeeping"]
          restartPolicy: OnFailure
---