############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: batch/v1
kind: Job
metadata:
  name: netbox-migrate
  namespace: netbox
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: ghcr.io/eliasdhcom/netbox:latest
        imagePullPolicy: Always
        command: ["/opt/netbox/venv/bin/python", "/opt/netbox/netbox/manage.py", "migrate"]
      restartPolicy: OnFailure
---