############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 80
              protocol: TCP
          env:
            - name: ServerIP
              value: "0.0.0.0"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: WEBPASSWORD
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: pihole1-storage
              mountPath: /etc/pihole
            - name: pihole2-storage
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pihole1-storage
          persistentVolumeClaim:
            claimName: pihole1-pvc
        - name: pihole2-storage
          persistentVolumeClaim:
            claimName: pihole2-pvc
---