############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: WebServer006-letsencrypt-issuer
  namespace: WebServer006
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@eliasdh.com
    privateKeySecretRef:
      name: WebServer006-letsencrypt-issuer-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
---