############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Service
metadata:
  name: webserver003-frontend-service
  namespace: webserver003
spec:
  selector:
    app: webserver003-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webserver003-backend-service
  namespace: webserver003
spec:
  selector:
    app: webserver003-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webserver003-mysql-service
  namespace: webserver003
spec:
  selector:
    app: webserver003-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---